### ISSUE TITLE
Change gripper dimensions

### ISSUE THREAD

**Issue by BryanBetancur** [luyh20/FGC-GraspNet#2]
Thanks for share your code. What do I need to change to work with a different gripper sizes? Like finger length and width, maximum opening, etc.

**Comment by luyh20** [comment]
The geometry of gripper in visualization from Open3d can be changed in GraspnetAPI module, please refer to [https://github.com/graspnet/graspnetAPI/blob/master/graspnetAPI/grasp.py.](url) But this kind of change is not equivalent to correcting the actual gripper because the confidence score labels have generated under initial gripper. In my experience, if you want your gripper to be more consistent with the dataset, you could find the difference between the actual contact points and the contact points in visualization. Correct this difference by gripper length compensation with moving robot arm TCP.

**Comment by BryanBetancur** [comment]
Thank You.
